### ISSUE TITLE
Dart package matter IoT missing repo link

### ISSUE THREAD

**Issue by guyluz11** [OpenIoTHub/OpenIoTHub#7]
I found [matter IoT](https://pub.dev/packages/matter) package in pub.dev but it missing a link to the page

### Repository (GitHub)

Even if the package is not ready please add a link so people can keep track of the package.

![Screenshot_20230603_104400_Firefox](https://github.com/OpenIoTHub/OpenIoTHub/assets/9304740/ff5be86d-e0ec-4ed4-997b-633421cb357d)

![Screenshot_20230603_104612_Firefox](https://github.com/OpenIoTHub/OpenIoTHub/assets/9304740/e8ea29f7-1315-4190-9006-b59323f20a04)

**Comment by IoTServ** [comment]
Sorry,I will use it for IoT [UI package](https://github.com/OpenIoTHub/openiothub_plugin),and I also registered the package for rust [matter-rs](https://crates.io/crates/matter-rs) for MUC or gateway usage

**Comment by guyluz11** [comment]
Can you add here a linke to this package
https://pub.dev/packages/matter GitHub repo please?
